name: validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  main:
    strategy:
      matrix:
        eslint: [7.12.1, 7, 8.0.0, 8]
        node: [12.22.0, 12, 14.17.0, 14, 16.0.0, 16]
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Install ESLint v${{ matrix.eslint }}
        run: npm install --no-save --force eslint@${{ matrix.eslint }}

      - name: ▶️ Run tests
        run: npm test
